# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\yi\Desktop\Monitors1\MonitorsUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import serial
import threading


# Establish serial connection with Arduino
ser = serial.Serial('COM7', 9600)  # Change 'COM3' to the appropriate port


           

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1091, 819)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tempNo = QtWidgets.QLabel(self.centralwidget)
        self.tempNo.setObjectName("tempNo")
        font = QtGui.QFont()
        font.setPointSize(50)  # Set the desired font size, e.g., 16

        # Set the font for the QLabel
        self.tempNo.setFont(font)
        
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        
        layout = QtWidgets.QHBoxLayout()
        self.label.setLayout(layout)

        # Load the icon image
        icon = QtGui.QPixmap("untitled folder\icons\hermometer.png")  # Replace "path_to_your_icon.png" with the actual path to your icon image file

        # Scale the icon pixmap
        scaled_icon = icon.scaled(50, 50)  # Adjust the size as needed, e.g., 50x50 pixels

        # Create a QLabel for the icon
        icon_label = QtWidgets.QLabel()
        icon_label.setPixmap(scaled_icon)
        
        
        # Set the icon pixmap to the QLabel
        # self.label.setPixmap(scaled_icon)
        self.label.setObjectName("label")
        self.label.setPixmap(scaled_icon)
        
        self.tempState = QtWidgets.QLabel(self.centralwidget)
        self.tempState.setObjectName("tempState")
        

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        icon2 = QtGui.QPixmap("untitled folder\icons\humidity.png") 
        self.label_2.setPixmap(icon2)
        self.humidityNo = QtWidgets.QLabel(self.centralwidget)
        self.humidityNo.setObjectName("humidityNo")
        self.humidityNo.setFont(font)
        self.label2 = QtWidgets.QLabel(self.centralwidget)
       
        
        layout2 = QtWidgets.QHBoxLayout()
        self.label2.setLayout(layout2)
        

        # Load the icon image
         # Replace "path_to_your_icon.png" with the actual path to your icon image file

        # Scale the icon pixmap
        scaled_icon2 = icon2.scaled(50, 50)  # Adjust the size as needed, e.g., 50x50 pixels

        # Create a QLabel for the icon
        icon_label2 = QtWidgets.QLabel()
        icon_label2.setPixmap(scaled_icon2)
        icon3 = QtGui.QPixmap("untitled folder\icons\cardiogram.png") 
        scaled_icon3 = icon3.scaled(50, 50)  # Adjust the size as needed, e.g., 50x50 pixels

        # Create a QLabel for the icon
        icon_label3 = QtWidgets.QLabel()
        icon_label3.setPixmap(scaled_icon3)
        # layout2.addWidget(icon_label2)
        # layout2.addWidget(self.label2)
        # layout2.setAlignment(QtCore.Qt.AlignRight)
        self.label_2.setObjectName("label_2")

        

        
        

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        
        icon4 = QtGui.QPixmap("untitled folder\icons\onlamp.png") 
        scaled_icon4 = icon4.scaled(50, 50)  # Adjust the size as needed, e.g., 50x50 pixels
        # Create a QLabel for the icon
        self.icon_label4 = QtWidgets.QLabel()
        self.icon_label4.setPixmap(scaled_icon4)
        
       



        
        self.heartNo = QtWidgets.QLabel(self.centralwidget)
        self.heartNo.setObjectName("heartNo")
        self.heartNo.setFont(font)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1091, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.tempNo.setText("Temperature")
        self.humidityNo.setText("Humidity")
        self.heartNo.setText("BPM")
        self.label_4.setFont(font)
        

        t1= threading.Thread(target=self.read_data)
        t1.start()
        self.gridLayout.addWidget(self.label, 0, 0, 3, 1)
        self.gridLayout.addWidget(self.tempNo, 0, 2,3, 1)
        self.gridLayout.addWidget(icon_label,0,1,3,1)

        
        self.gridLayout.addWidget(self.label_2, 1, 0, 6, 1)
        self.gridLayout.addWidget(icon_label2,1,1,6,1)
        self.gridLayout.addWidget(self.humidityNo, 1, 2, 6, 1)
        
        self.gridLayout.addWidget(icon_label3,2,1,9,1)
        self.gridLayout.addWidget(self.label_3, 2, 0, 9, 1)
        self.gridLayout.addWidget(self.heartNo, 2, 2, 9, 1)

        self.gridLayout.addWidget(self.icon_label4,3,1,12,1)
        self.gridLayout.addWidget(self.tempState, 3, 0, 12, 1)
        self.gridLayout.addWidget(self.label_4, 3, 2, 12, 1)
        
      

    def retranslateUi(self, MainWindow):
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
            self.tempNo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">TextLabel</span></p></body></html>"))
            self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:40pt; color:#ff0000;\">Temperature:</span></p></body></html>"))
            self.tempState.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:40pt;\">Lamp:</span></p></body></html>"))
            self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:40pt; color:#00ff7f;\">ON</span></p></body></html>"))
            self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:40pt;\">Humidity:</span></p></body></html>"))
            self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:40pt; color:#0000ff;\">Heart Rate:</span></p></body></html>"))
            self.humidityNo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">TextLabel</span></p></body></html>"))
            self.heartNo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">TextLabel</span></p></body></html>"))
                

    def toggleLamp(self,state):
         _translate = QtCore.QCoreApplication.translate

         if state=="ON":
              icon4=QtGui.QPixmap("untitled folder\icons\onlamp.png")
              scaled_icon4=icon4.scaled(50,50)
              self.icon_label4.setPixmap(scaled_icon4)
              self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:40pt; color:#00ff7f;\">ON</span></p></body></html>"))
         else:
              icon4=QtGui.QPixmap("untitled folder\icons\offlamp.png")
              scaled_icon4=icon4.scaled(50,50)
              self.icon_label4.setPixmap(scaled_icon4)
              self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:40pt; color:#ff0000;\">OFF</span></p></body></html>"))
  

    def read_data(self):
        while True:
            if ser.in_waiting > 0:
                alldata = ser.readline().decode('utf-8')
                alldata=alldata.split("|")
                self.tempNo.setText(alldata[3])
                self.humidityNo.setText(alldata[2])
                
                self.heartNo.setText(alldata[1])
                self.toggleLamp(alldata[4][0:2])

                
      

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
